FROM centos

COPY dce-app-entrypoint /work/dce-app-entrypoint
COPY echo.sh /work/echo.sh

ENV DAE_NETWORK='mac'
ENV DAE_SEGMENT='^172\.17\.\d{1,3}.\d{1,3}$'
ENV DAE_OUTPUT='/tmp/env.sh'

CMD /work/dce-app-entrypoint && source /tmp/env.sh && /work/echo.sh